<pickingOrderBeginEventMessage xmlns="http://www.xmlns.walmartstores.com/SuppyChain/FulfillmentManagement/GlobalIntegeratedFulfillment/Picking/OrderBeginEvent/1.0/" xmlns:flt="http://www.xmlns.walmartstores.com/Fault/datatypes/MessageFault/1.0/" xmlns:hdr="http://www.xmlns.walmartstores.com/Header/datatypes/MessageHeader/1.4/">
  <hdr:MessageHeader>
    <hdr:SubId>SUB-EIC-ALPHAEVNT-V1</hdr:SubId>
    <hdr:CnsmrId>CON-ALPHA-V1</hdr:CnsmrId>
    <hdr:SrvcNm>FulfillmentPicking.subSystemOrderPickingStarted</hdr:SrvcNm>
    <hdr:AppId>ALPHA</hdr:AppId>
    <hdr:TranId>${eventPayload.fulfillmentOrder.orderNbr}</hdr:TranId>
    <hdr:Version>1.0</hdr:Version>
  </hdr:MessageHeader>
  <MessageBody>
    <RoutingInfo>
      <SourceNode>
        <location>
          <countryCode>US</countryCode>
        </location>
        <cNodeID>ALPHA</cNodeID>
      </SourceNode>
      <DestinationNode>
        <location>
          <countryCode>US</countryCode>
        </location>
        <nodeID>2142</nodeID>
      </DestinationNode>
    </RoutingInfo>
    <orderBeginEvent>
      <node>
        <nodeId>2142</nodeId>
        <countryCode>US</countryCode>
      </node>
      <fulfillmentOrders>
        <fulfillmentOrder>
          <orderNbr>${eventPayload.fulfillmentOrder.orderNbr}</orderNbr>
          <priorityCode>${eventPayload.fulfillmentOrder.priorityCode}</priorityCode>
          <assignedPickUserId>alpha</assignedPickUserId>
        </fulfillmentOrder>
      </fulfillmentOrders>
    </orderBeginEvent>
    <MessageExtensions/>
  </MessageBody>
</pickingOrderBeginEventMessage>
