fusion:
  brokers:
    - channel: NA
      hostUrl: 'tcp://fusion-activemq:61616'
      brokerId: fusionBroker
      jmsProvider: ACTIVEMQ
      queueManagerName: NA
      sendSessionCacheSize: 10
      userName: admin
  retryPolicies:
    - policyType: REALTIME
      maxAttempt: 3
      backoffMS: 1000
      type: Fixed
    - policyType: OFFLINE
      maxAttempt: 5
      backoffMS: 2000
      type: Exponential
  usecases:
    - name: OrderDropEvent
      version: 1
      activeConfig: adapterConfig
      configs:
        - name: adapterConfig
          adapters:
            - adapterType: outbound
              trasnportType: JMS
              usecaseResult: SUCCESS
              brokerId: fusionBroker
              queueName: FUSION.ORDER.IN
            - adapterType: outbound
              trasnportType: JMS
              usecaseResult: SUCCESS
              brokerId: fusionBroker
              queueName: FUSION.AUDIT.IN
              transformationType: DOMAIN_EVENT_TRANSFORMER
            - adapterType: outbound
              trasnportType: JMS
              usecaseResult: FAILURE
              brokerId: fusionBroker
              queueName: FUSION.ORDER.ERROR
    - name: OrderDropEventReader
      version: 1
      activeConfig: adapterConfig
      configs:
        - name: adapterConfig
          adapters:
            - adapterType: outbound
              trasnportType: JMS
              usecaseResult: SUCCESS
              brokerId: fusionBroker
              queueName: US.FUSION.ALPHA.IN.QUEUE
              template: PickingSubsystemOrderReleaseMessage.vm
              transformationType: TEMPLATE_TRANSFORMER
            - adapterType: outbound
              trasnportType: JMS
              usecaseResult: SUCCESS
              brokerId: fusionBroker
              queueName: FUSION.AUDIT.IN
              transformationType: DOMAIN_EVENT_TRANSFORMER
            - adapterType: outbound
              trasnportType: JMS
              usecaseResult: FAILURE
              brokerId: fusionBroker
              queueName: US.FUSION.ALPHA.ERROR.QUEUE

    - name: PickBeginEvent
      version: 1
      activeConfig: adapterConfig
      configs:
        - name: adapterConfig
          adapters:
            - adapterType: outbound
              trasnportType: REST
              usecaseResult: SUCCESS
              hostName: developer.api.us.stg.walmart.com
              port: 443
              protocol: https
              methodType: POST
              uriTemplate: PickBeginEvent_uri_walmart.vm
              requestBodyTemplate: PickingOrderBeginEventMessage_requestBody.vm
              requestHeaderTemplate: PickBeginEvent_requestHeader.vm
              templateCustomizer: PickBeginOutboundCustomizer
              transformationType: TEMPLATE_TRANSFORMER
            - adapterType: outbound
              trasnportType: JMS
              usecaseResult: SUCCESS
              brokerId: fusionBroker
              queueName: FUSION.AUDIT.IN
              transformationType: DOMAIN_EVENT_TRANSFORMER
            - adapterType: outbound
              trasnportType: JMS
              usecaseResult: FAILURE
              brokerId: fusionBroker
              queueName: FUSION.PICK.BEGIN.OUTBOUND.ERROR


    - name: PickEndEvent
      version: 1
      activeConfig: adapterConfig
      configs:
        - name: adapterConfig
          adapters:
            - adapterType: outbound
              trasnportType: REST
              usecaseResult: SUCCESS
              hostName: developer.api.us.stg.walmart.com
              port: 443
              protocol: https
              methodType: POST
              uriTemplate: PickEndEvent_uri_walmart.vm
              requestBodyTemplate: PickingSubSystemOrderCompleteMessage_requestBody.vm
              requestHeaderTemplate: PickEndEvent_requestHeader.vm
              transformationType: TEMPLATE_TRANSFORMER
              templateCustomizer: PickEndOutboundCustomizer
            - adapterType: outbound
              trasnportType: JMS
              usecaseResult: SUCCESS
              brokerId: fusionBroker
              queueName: FUSION.AUDIT.IN
              transformationType: DOMAIN_EVENT_TRANSFORMER
            - adapterType: outbound
              trasnportType: JMS
              usecaseResult: FAILURE
              brokerId: fusionBroker
              queueName: FUSION.PICK.END.OUTBOUND.ERROR
spring:
  datasource:
    platform: mariadb
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb:failover://fusion-mariadb:3306/fusion?autoReconnect=true
    username: fusion
    password: fusion
    timeBetweenEvictionRunsMillis: 1000
    testWhileIdle: true
  liquibase:
    enabled: false
  hikari:
    connectionTimeout: 30000
    idleTimeout: 30000
    maxLifetime: 2000000
    maximumPoolSize: 20
    minimumIdle: 5
    poolName: SpringBootJPAHikariCP
  jpa:
    ddl-auto: ''
    show-sql: true
hash:
  key: d8fee0ad8d9960fb4e02ed246b7f0ea51a2e18645514b166abe84f72106590c2