fusion:
  brokers:
    - channel: NA
      hostUrl: 'tcp://127.0.0.1:61616'
      brokerId: fusionBroker
      jmsProvider: ACTIVEMQ
      queueManagerName: NA
      sendSessionCacheSize: 10
      userName: admin
  retryPolicies:
    - policyType: REALTIME
      maxAttempt: 3
      backoffMS: 1000
      type: Fixed
    - policyType: OFFLINE
      maxAttempt: 5
      backoffMS: 2000
      type: Exponential
  usecases:
    - name: OrderCreateViaREST
      version: 1
      activeConfig: adapterConfig
      configs:
        - name: adapterConfig
          adapters:
            - adapterType: outbound
              trasnportType: JMS
              usecaseResult: SUCCESS
              brokerId: fusionBroker
              queueName: FUSION.ORDER.OUT.QUEUE
            - adapterType: outbound
              trasnportType: JMS
              usecaseResult: SUCCESS
              brokerId: fusionBroker
              queueName: FUSION.AUDIT.IN
              transformationType: DOMAIN_EVENT_VELOCITY_TRANSFORMER
    - name: OrderCreateViaJMS
      version: 1
      activeConfig: adapterConfig
      configs:
        - name: adapterConfig
          adapters:
            - adapterType: outbound
              trasnportType: REST
              usecaseResult: SUCCESS
              hostName: httpbin.org
              port: 443
              protocol: https
              methodType: POST
              uriTemplate: OrderCreateJMSEvent_uri
              requestBodyTemplate: OrderCreateJMSEvent_requestBody
              requestHeaderTemplate: OrderCreateJMSEvent_requestHeader
              templateCustomizer: com.scoperetail.fusion.orchestrator.config.plugins.order.create.OrderCreateOutboundCustomizer
              transformationType: FTL_TEMPLATE_TRANSFORMER
            - adapterType: outbound
              trasnportType: JMS
              usecaseResult: SUCCESS
              brokerId: fusionBroker
              queueName: FUSION.AUDIT.IN
              transformationType: DOMAIN_EVENT_FTL_TRANSFORMER              
                          
  credentials:
    hash: f3f98da4f4ffab537791fa4ff11d3473c070cdf802ea41182f8125a4c5b4b193
spring:
  datasource:
    platform: mariadb
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb:failover://localhost:3306/fusion?autoReconnect=true
    username: fusion
    password: fusion
    timeBetweenEvictionRunsMillis: 1000
    testWhileIdle: true
  liquibase:
    enabled: false
  hikari:
    connectionTimeout: 30000
    idleTimeout: 30000
    maxLifetime: 2000000
    maximumPoolSize: 20
    minimumIdle: 5
    poolName: SpringBootJPAHikariCP
  jpa:
    ddl-auto: ''
    show-sql: true