fusion:
  brokers:
    - channel: NA
      hostUrl: 'tcp://127.0.0.1:61615'
      brokerId: mcsBroker
      jmsProvider: ACTIVEMQ
      queueManagerName: NA
      sendSessionCacheSize: 10
      userName: admin
      owner: MCS
    - channel: NA
      hostUrl: 'tcp://127.0.0.1:61616'
      brokerId: fusionBroker
      jmsProvider: ACTIVEMQ
      queueManagerName: NA
      sendSessionCacheSize: 10
      userName: admin
      owner: FUSION
    - channel: NA
      hostUrl: 'tcp://127.0.0.1:61617'
      brokerId: GIFBroker
      jmsProvider: ACTIVEMQ
      queueManagerName: NA
      sendSessionCacheSize: 10
      userName: admin
      owner: GIF
  retryPolicies:
    - policyType: REALTIME
      maxAttempt: 3
      backoffMS: 1000
      type: Fixed
    - policyType: OFFLINE
      maxAttempt: 5
      backoffMS: 2000
      type: Exponential
  usecases:
    - name: OrderDropEvent
      version: 1
      activeConfig: adapterConfig
      configs:
        - name: adapterConfig
          adapters:
            - adapterType: outbound
              trasnportType: JMS
              usecaseResult: SUCCESS
              brokerId: fusionBroker
              queueName: ORDER.DROP.OUTBOUND
            - adapterType: outbound
              trasnportType: JMS
              usecaseResult: SUCCESS
              brokerId: fusionBroker
              queueName: AUDIT.IN
            - adapterType: outbound
              trasnportType: JMS
              usecaseResult: FAILURE
              brokerId: fusionBroker
              queueName: ORDER.DROP.ERROR
    - name: OrderDropEventReader
      version: 1
      activeConfig: adapterConfig
      configs:
        - name: adapterConfig
          adapters:
            - adapterType: outbound
              trasnportType: JMS
              usecaseResult: SUCCESS
              brokerId: GIFBroker
              queueName: ORDER.DROP.READER.OUTBOUND
            - adapterType: outbound
              trasnportType: JMS
              usecaseResult: SUCCESS
              brokerId: fusionBroker
              queueName: AUDIT.IN
            - adapterType: outbound
              trasnportType: JMS
              usecaseResult: FAILURE
              brokerId: fusionBroker
              queueName: ORDER.DROP.OUTBOUND.ERROR
             
    - name: PickBeginEvent
      version: 1
      activeConfig: adapterConfig
      configs:
        - name: adapterConfig
          adapters:
            - adapterType: outbound
              trasnportType: JMS
              usecaseResult: SUCCESS
              brokerId: fusionBroker
              queueName: AUDIT.IN
            - adapterType: outbound
              trasnportType: REST
              usecaseResult: SUCCESS
              hostName: httpbin.org
              port: 443
              protocol: https
              methodType: POST
              uriTemplate: uri.vm
              requestBodyTemplate: requestBody.vm
              requestHeaderTemplate: requestHeader.vm
            - adapterType: outbound
              trasnportType: JMS
              usecaseResult: FAILURE
              brokerId: fusionBroker
              queueName: PICK.BEGIN.OUTBOUND.BO
              
    - name: PickEndEvent
      version: 1
      activeConfig: adapterConfig
      configs:
        - name: adapterConfig
          adapters:
            - adapterType: outbound
              trasnportType: JMS
              usecaseResult: SUCCESS
              brokerId: fusionBroker
              queueName: AUDIT.IN
            - adapterType: outbound
              trasnportType: REST
              usecaseResult: SUCCESS
              hostName: httpbin.org
              port: 443
              protocol: https
              methodType: POST
              uriTemplate: uri.vm
              requestBodyTemplate: requestBody.vm
              requestHeaderTemplate: requestHeader.vm
            - adapterType: outbound
              trasnportType: JMS
              usecaseResult: FAILURE
              brokerId: fusionBroker
              queueName: PICK.END.OUTBOUND.BO                     