fusion:
  brokers:
    - channel: NA
      hostUrl: 'tcp://127.0.0.1:61616'
      brokerId: scopeBroker
      jmsProvider: ACTIVEMQ
      queueManagerName: NA
      sendSessionCacheSize: 10
      userName: admin
      owner: SCOPE
    - channel: NA
      hostUrl: 'tcp://127.0.0.1:61617'
      brokerId: thirdPartyBroker
      jmsProvider: ACTIVEMQ
      queueManagerName: NA
      sendSessionCacheSize: 10
      userName: admin
      owner: GIF
  retryPolicies:
    - policyType: REALTIME
      maxAttempt: 3
      backoffMS: 1000
      type: Fixed
    - policyType: OFFLINE
      maxAttempt: 5
      backoffMS: 2000
      type: Exponential
  usecases:
    - name: OrderDropEvent
      version: 1
      activeConfig: adapterConfig
      configs:
        - name: adapterConfig
          logLevel: DEBUG
          adapters:
            - adapterType: outbound
              type: jms
              usecaseResult: SUCCESS
              brokerId: scopeBroker
              queueName: ORDER.DROP.READER
            - adapterType: outbound
              type: jms
              usecaseResult: SUCCESS
              brokerId: scopeBroker
              queueName: AUDIT.IN
            - adapterType: outbound
              type: jms
              usecaseResult: FAILURE
              brokerId: scopeBroker
              queueName: ORDER.DROP.ERROR
              
    - name: OrderDropEventReader
      version: 1
      activeConfig: adapterConfig
      configs:
        - name: adapterConfig
          logLevel: DEBUG
          adapters:
            - adapterType: outbound
              type: jms
              usecaseResult: SUCCESS
              brokerId: thirdPartyBroker
              queueName: ORDER.DROP.OUTBOUND
            - adapterType: outbound
              type: jms
              usecaseResult: SUCCESS
              brokerId: scopeBroker
              queueName: AUDIT.IN            
            - adapterType: outbound
              type: jms
              usecaseResult: FAILURE
              brokerId: thirdPartyBroker
              queueName: ORDER.DROP.OUTBOUND.ERROR

            
              
              