# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  marvel: scoperetail/marvel@dev:c380d47

workflows:
  build-and-test:
    jobs:
      - marvel/maven-deploy:
          context:
            - SLACK
            - ARTIFACTORY
          filters:
            branches:
              ignore:
                - master
                - - /HOTFIX-.*/
      - marvel/docker-publish:
          context:
            - OSSRH
            - SLACK
            - ARTIFACTORY
            - DOCKER_SCOPERETAIL
          filters:
            branches:
              only: 
                - master
                - /HOTFIX-.*/
